
SOLVER:
  BASE_LR: 0.1
  WEIGHT_DECAY: 0.0005
  IMS_PER_BATCH: 256
  MILE_STONES: [20, 40, 60]

INPUT:
  PIXEL_MEAN: [0.507, 0.487, 0.441]
  PIXEL_STD: [0.267, 0.256, 0.276]

DATASETS:
  NAME: "CIFAR100"

MODEL:
  NUM_CLASSES: 100

TEST:
  IMS_PER_BATCH: 200

METRIC:
  NAME: "Softmax"
  S: 7.5
  M: 0.35
  N: 1

ARCHI:
  NAME: "VGG"

OUTPUT_DIR: "./checkpoint/cifar100"
